framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Comment
            initial_marking: submitted
            places:
                - submitted
                - ham
                - potential_spam
                - spam
                - rejected
                - ready
                - published
            transitions:
                accept:
                    from: submitted
                    to:   ham
                might_be_spam:
                    from: submitted
                    to:   potential_spam
                reject_spam:
                    from: submitted
                    to:   spam
                publish:
                    from: potential_spam
                    to:   ready
                reject:
                    from: potential_spam
                    to:   rejected
                publish_ham:
                    from: ham
                    to:   ready
                reject_ham:
                    from: ham
                    to:   rejected
                optimize:
                    from: ready
                    to: published
        blog_post:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\BlogPost
            initial_marking: DRAFT
            places:
                - DRAFT
                - REVIEW
                - APPROVED
                - REJECTED
                - PUBLISHED
            transitions:
                REVIEW:
                    from: DRAFT
                    to: REVIEW
                APPROVED:
                    from: REVIEW
                    to: APPROVED
                REJECTED:
                    from: REVIEW
                    to: REJECTED
                PUBLISHED:
                    from: APPROVED
                    to: PUBLISHED
                DRAFT:
                    from: REJECTED
                    to: DRAFT